name: 'Build and Push to GHCR'

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build go binary
        run: ./build.sh

      - name: Docker build
        run: |
          docker build -t sidecar .

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker image tag sidecar ghcr.io/code-growers/config-reloader-sidecar:${{ github.ref_name }}
          docker push ghcr.io/code-growers/config-reloader-sidecar:${{ github.ref_name }}
